### ISSUE TITLE
Is there a forum where questions can be asked?

### ISSUE THREAD

**Issue by amortaza** [edgetechlabs/fz-android-sdk#1]
Sorry to leave comment here, I did not know where else to ask.

I am trying to write an android (sdk 27) application that connects to fret zealot.

I followed your instructions, but I am not able to connect to my fret zealot.

I simply want to log when the bluetooth device is simply found - nothing more.

Here is my MainActivity:

******************************************************************************************************

public class MainActivity extends AppCompatActivity {

    private LEDBLELib mLib;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        mLib = LEDBLELib.getInstance(this);

        mLib.startScan(new BluetoothAdapter.LeScanCallback() {

            @Override
            public void onLeScan(BluetoothDevice device, int rssi, byte[] scanRecord) {
                Log.v("ace_log","YES!");
            }
        });
    }
}

******************************************************************************************************
The log YES! is never reached.

My AndroidManifest.xml looks like:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.ace.hellofret">

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <permission android:name="android.permission.BLUETOOTH" android:label="BLUETOOTH" />
    <permission android:name="android.permission.BLUETOOTH_ADMIN" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service android:name="com.fz.blelib.BluetoothLeService" android:enabled="true"/>

    </application>

</manifest>

******************************************************************************************************
I have my fret zealot on.

My Nexus 6P is able to connect to the fret zealot using the official app.

Bluetooth is ON / location is ON

Do you have any ideas please?

**Comment by tolster710** [comment]
Hi! We'll update the docs to include this, but in Android, we need a few additional permissions for BLE connections.
In your Android Manifest, let's add:
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

This should allow you to discover Bluetooth devices

**Comment by amortaza** [comment]
I left this project for a very long time, but I had to get back! I was able to successfully communicate and light up the lights on every fret and string!  Time to start writing some real apps.  I want to thank you @tolster710 for the initial help.

**Comment by tolster710** [comment]
Hey @amortaza Great to hear from you again! We're still here and happy to have you back! While there are no recent updates to the SDK, everything continues to operate as expected, and we're excited to see what you come up with.

You can message me directly by emailing support @ fretzealot.com and I'll be happy to provide all the answers I can :)
